name: django-pghistory
channels:
  - conda-forge
dependencies:
  - python==3.12.0
  - poetry==1.6.1
  - pip==23.2.1
  - postgresql==16.0
variables:
  DATABASE_URL: "postgres://postgres@localhost:5432/pghistory_local"
  EXEC_WRAPPER: ""
