[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 99
target-version = ['py37']

[tool.coverage.run]
branch = true
source = ["pghistory"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise AssertionError",
    "raise NotImplementedError",
    "pass",
    "pytest.mark.skip"
]
show_missing = true
fail_under = 100

[tool.poetry]
name = "django-pghistory"
packages = [
  { include = "pghistory" }
]
exclude = [
  "*/tests/"
]
version = "2.4.2"
description = "History tracking for Django and Postgres"
authors = ["Wes Kendall"]
classifiers = [
  "Framework :: Django",
  "Framework :: Django :: 2.2",
  "Framework :: Django :: 3.2",
  "Framework :: Django :: 4.0",
  "Framework :: Django :: 4.1",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3 :: Only",
  "Framework :: Django",
]
license = "BSD-3-Clause"
readme = "README.rst"
homepage = "https://github.com/Opus10/django-pghistory"
repository = "https://github.com/Opus10/django-pghistory"
documentation = "https://django-pghistory.readthedocs.io"

[tool.poetry.dependencies]
python = ">=3.7.0,<4"
django = ">=2"
importlib_metadata = { version = ">=4", python = "~3.7" }
django-pgtrigger = ">=3.2.0"

[tool.poetry.dev-dependencies]
black = "22.6.0"
dj-database-url = "0.5.0"
django-dynamic-fixture = "3.1.1"
django-extensions = "3.1.3"
flake8 = "3.9.2"
flake8-bugbear = "22.1.11"
flake8-comprehensions = "3.8.0"
flake8-import-order = "0.18.1"
flake8-logging-format = "0.6.0"
flake8-mutable = "1.2.0"
git-tidy = "1.1.2"
myst-parser = "0.18.0"
packaging = ">=19.2"
pip = "*"
poetry-core = "1.1.0rc3"
pre-commit = "2.13.0"
psycopg2-binary = "2.8.6"
pytest = "7.0.0"
pytest-cov = "3.0.0"
pytest-django = "4.5.2"
pytest-mock = "3.6.1"
requests = "2.25.1"
Sphinx = "4.4.0"
sphinx-rtd-theme = "1.0.0"
footing = "*"
tox = "3.24.5"
zipp = "3.4.1"

[tool.pytest.ini_options]
xfail_strict = true
addopts = "--reuse-db"
testpaths = "pghistory/tests"
norecursedirs = ".venv"
DJANGO_SETTINGS_MODULE = "settings"
